#!/bin/bash

# installing ftp server and client
sudo pip3 install pyftpdlib
sudo apt install lftp

# creating files to upload
#fallocate -l 1GB 1gb-file
fallocate -l 512mb /home/mn-wifi/512mb-file

sudo cp httpclient httpserver ftpclient ftpserver /usr/bin/
