#!/bin/bash

# Check if at least one argument is passed
if [ $# -eq 1 ]; then
    hostname=$1
    iterations=-1
else
    if [ $# -eq 2 ]; then
       hostname=$1
       iterations=$2
    else
       echo "Syntax: httpclient hostname or httpclient hostname iterations"
       exit 1
    fi
fi

# Initialize variables for statistics
total_requests=0
total_time=0

# Function to calculate and display statistics
display_statistics() {
    if [ $total_requests -gt 0 ]; then
        average_time=$(bc -l <<< "scale=4; $total_time / $total_requests")
        printf "statistics after %d requests:\n" $total_requests
        printf "total time: %.2f ms\n" $total_time
        printf "average time per request: %.2f ms\n" $average_time
    fi
    exit 0
}

# Set up a trap for Ctrl+C to call the statistics function
trap 'display_statistics' SIGINT

while [[ $iterations -ne 0 ]]; do
    response_time=$(curl -o /dev/null -s -w '%{time_total}\n' "$hostname:8080")
    # Check the exit code of the command
    if [ $? -ne 0 ]; then
        echo "curl execution failed"
        exit 1
    fi

    response_time="${response_time//[^0-9.]/}"

    # Set the LC_NUMERIC environment variable to use a comma as the decimal separator
    LC_NUMERIC="en_US.UTF-8"  # Adjust the locale as needed

    # convert response time from seconds to ms
    response_time=$(echo "$response_time * 1000" | bc)

    printf "response time: %.2f ms\n" $response_time

    # Update statistics
    total_requests=$((total_requests + 1))
    total_time=$(bc -l <<< "scale=2; $total_time + $response_time")

    # decrease iterations number
    iterations=$((iterations - 1))

    sleep 1
done

display_statistics
